package service

const (
	UNAUTHORIZED = "UNAUTHORIZED"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	INVALID_REQUEST_HEADER = "INVALID_REQUEST_HEADER"
	INVALID_PATH_PARAMETER = "INVALID_PATH_PARAMETER"
	INVALID_REQUEST_BODY = "INVALID_PATH_PARAMETER"
	RETRY = "RETRY"
)
