export const quizsetdata = {
        "quizset_name":"형식언어",
        "class_id":"CS_295",
        "quizzes":[
           {
              "id":0,
              "type":"mul_choices",
              "question":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam ",
              "answer":"0,3",
              "content":{
                 "description":"",
                 "choices":[
                    {
                       "id":0,
                       "choice":"선택지 1"
                    },
                    {
                       "id":1,
                       "choice":"선택지 2"
                    },
                    {
                       "id":2,
                       "choice":"ㅁㄷㄹㄷㅈ"
                    },
                    {
                       "id":3,
                       "choice":""
                    }
                 ]
              }
           },
           {
              "id":1,
              "type":"essay",
              "question":"문제 2",
              "answer":"ㅁ재ㅑ더럄ㄹ재ㅑ",
              "content":{
                 "description":""
              }
           },
           {
              "id":2,
              "type":"essay",
              "question":"ㅁㅈㄹ댜ㅐㅓ",
              "answer":"ㅐㅑㅁ점ㄹㅈ댜ㅓ",
              "content":{
                 "description":""
              }
           },
           {
              "id":3,
              "type":"essay",
              "question":"ㅁ재댜러ㅐㅑ",
              "answer":"ㅐㅑ더랴ㅐ머쟈ㅐ러ㅑㅐㅈㅇㄹ",
              "content":{
                 "description":""
              }
           }
        ]
     }